/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Bram Tempelaere (https://sketchfab.com/tempelaerebram)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylised-ww1-plane-2643dbf0f15d457bb4e1bfa38cc44c23
Title: Stylised WW1 plane
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const WWPlane = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/stylised_ww1_plane.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="6da8880dcbc8425a9ae58202804f4326fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="group">
                  <group name="GEO">
                    <group name="plane_GEO">
                      <group
                        name="model_geo"
                        position={[1.139, 223.086, 53.588]}
                        rotation={[-0.175, -0.002, 0.004]}
                      >
                        <group
                          name="polySurface4"
                          position={[-1.139, -201.196, -0.426]}
                        >
                          <group name="polySurface18">
                            <group name="polySurface23">
                              <group name="polySurface25">
                                <group name="polySurface35">
                                  <mesh
                                    name="polySurface35_lambert2_0"
                                    castShadow
                                    receiveShadow
                                    geometry={
                                      nodes.polySurface35_lambert2_0.geometry
                                    }
                                    material={materials.lambert2}
                                  />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group
                        name="outline_geo"
                        position={[1.677, 223.469, 53.588]}
                        rotation={[-0.175, -0.002, 0.004]}
                      >
                        <group
                          name="polySurface8"
                          position={[-1.677, -201.579, -0.426]}
                        >
                          <group
                            name="polySurface2"
                            position={[-255.534, 205.983, 0.385]}
                            rotation={[-0.566, -0.06, -0.023]}
                          >
                            <mesh
                              name="polySurface2_lambert2_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.polySurface2_lambert2_0.geometry}
                              material={materials.lambert2}
                            />
                            <mesh
                              name="polySurface2_lambert4_0"
                              castShadow
                              receiveShadow
                              geometry={nodes.polySurface2_lambert4_0.geometry}
                              material={materials.lambert4}
                            />
                          </group>
                          <group name="polySurface13">
                            <group
                              name="group1"
                              position={[-14.1, 1.781, 22.084]}
                              rotation={[-0.109, 0.013, -0.07]}
                            >
                              <group
                                name="polySurface17"
                                position={[-104.356, 282.74, 246.44]}
                                rotation={[-0.01, 0.016, 0.138]}
                              >
                                <mesh
                                  name="polySurface17_lambert4_0"
                                  castShadow
                                  receiveShadow
                                  geometry={
                                    nodes.polySurface17_lambert4_0.geometry
                                  }
                                  material={materials.lambert4}
                                />
                              </group>
                              <group
                                name="polySurface16"
                                position={[-67.542, 126.952, 231.803]}
                                rotation={[-0.018, 0.021, 0.146]}
                              >
                                <mesh
                                  name="polySurface16_lambert2_0"
                                  castShadow
                                  receiveShadow
                                  geometry={
                                    nodes.polySurface16_lambert2_0.geometry
                                  }
                                  material={materials.lambert2}
                                />
                                <mesh
                                  name="polySurface16_lambert4_0"
                                  castShadow
                                  receiveShadow
                                  geometry={
                                    nodes.polySurface16_lambert4_0.geometry
                                  }
                                  material={materials.lambert4}
                                />
                              </group>
                              <group
                                name="polySurface14"
                                position={[-70.308, 341.651, -270.432]}
                              >
                                <mesh
                                  name="polySurface14_lambert4_0"
                                  castShadow
                                  receiveShadow
                                  geometry={
                                    nodes.polySurface14_lambert4_0.geometry
                                  }
                                  material={materials.lambert4}
                                />
                              </group>
                              <group
                                name="polySurface15"
                                position={[-30.082, 187.529, -296.415]}
                              >
                                <mesh
                                  name="polySurface15_lambert4_0"
                                  castShadow
                                  receiveShadow
                                  geometry={
                                    nodes.polySurface15_lambert4_0.geometry
                                  }
                                  material={materials.lambert4}
                                />
                              </group>
                            </group>
                            <group name="polySurface21">
                              <group
                                name="group5"
                                position={[-14.1, 1.781, 22.084]}
                                rotation={[-0.109, 0.013, -0.07]}
                              >
                                <group
                                  name="polySurface19"
                                  position={[216.574, 164, -72.898]}
                                >
                                  <mesh
                                    name="polySurface19_lambert4_0"
                                    castShadow
                                    receiveShadow
                                    geometry={
                                      nodes.polySurface19_lambert4_0.geometry
                                    }
                                    material={materials.lambert4}
                                  />
                                </group>
                              </group>
                              <group name="polySurface30">
                                <mesh
                                  name="polySurface30_lambert4_0"
                                  castShadow
                                  receiveShadow
                                  geometry={
                                    nodes.polySurface30_lambert4_0.geometry
                                  }
                                  material={materials.lambert4}
                                />
                                <group
                                  name="group6"
                                  position={[-14.1, 1.781, 22.084]}
                                >
                                  <group
                                    name="polySurface37"
                                    position={[-154.925, 220.105, 13.506]}
                                    scale={[1, 1.047, 1.047]}
                                  >
                                    <mesh
                                      name="polySurface37_lambert2_0"
                                      castShadow
                                      receiveShadow
                                      geometry={
                                        nodes.polySurface37_lambert2_0.geometry
                                      }
                                      material={materials.lambert2}
                                    />
                                    <mesh
                                      name="polySurface37_lambert4_0"
                                      castShadow
                                      receiveShadow
                                      geometry={
                                        nodes.polySurface37_lambert4_0.geometry
                                      }
                                      material={materials.lambert4}
                                    />
                                  </group>
                                  <group
                                    name="group7"
                                    position={[-154.953, 220.446, -56.425]}
                                  >
                                    <group
                                      name="polySurface36"
                                      position={[0.044, 0.335, 0.265]}
                                      scale={[1, 1.059, 1.059]}
                                    >
                                      <mesh
                                        name="polySurface36_lambert2_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                          nodes.polySurface36_lambert2_0
                                            .geometry
                                        }
                                        material={materials.lambert2}
                                      />
                                      <mesh
                                        name="polySurface36_lambert4_0"
                                        castShadow
                                        receiveShadow
                                        geometry={
                                          nodes.polySurface36_lambert4_0
                                            .geometry
                                        }
                                        material={materials.lambert4}
                                      />
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="group8">
                  <group name="pasted__group">
                    <group name="pasted__GEO">
                      <group name="pasted__plane_GEO">
                        <group
                          name="pasted__outline_geo"
                          position={[1.677, 223.469, 53.588]}
                          rotation={[-0.175, -0.002, 0.004]}
                        >
                          <group
                            name="pasted__polySurface8"
                            position={[-1.677, -201.579, -0.426]}
                          >
                            <group name="pasted__polySurface13">
                              <group name="pasted__polySurface21">
                                <group
                                  name="pasted__group5"
                                  position={[-14.1, 1.781, 22.084]}
                                  rotation={[-0.109, 0.013, -0.07]}
                                >
                                  <group
                                    name="pasted__polySurface24"
                                    position={[215.772, 148.671, 66.254]}
                                    rotation={[-0.001, -0.014, 0.124]}
                                  >
                                    <mesh
                                      name="pasted__polySurface24_lambert4_0"
                                      castShadow
                                      receiveShadow
                                      geometry={
                                        nodes.pasted__polySurface24_lambert4_0
                                          .geometry
                                      }
                                      material={materials.lambert4}
                                    />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/stylised_ww1_plane.glb");

export default WWPlane;
